GET http://localhost:3000/posts

###
POST http://localhost:3000/login
Content-Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTUxNTk3NTF9.bxfl_6WZkoiyu_gf1Agx4itpjwwRS2XYL8FTWCRuptw

{
  "username": "Larry"
}