### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Larry"
}

### GetPosts
GET http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGFycnkiLCJpYXQiOjE2NTUyMzIzMjh9.fsSEAVSySDVfiUYWGkudAZXc8B28lc3pUXPY5cKDnAE
